remote_theme: christianezeani/panthera-jekyll

title: Kazumasa Shimari
subtitle: Assistant Professor

menu:
  - text: Japanese
    link: /
    icon: ""

  - text: English
    link: index.en.html
    icon: ""
  
social_icons:
  - name: github
    link: https://github.com/k-shimari
    icon: fab fa-github-square